<?php
/**
 * History section component
 * 
 * Usage:
 *   include '../includes/history-section.php';
 * 
 * Required variables in JavaScript scope:
 *   - problemHistory: array of history items
 *   - historyManager: history manager object (from initHistoryManager)
 * 
 * Optional: If historyManager is not available, will use localStorage fallback
 */
?>

<?php
if (!isset($lang)) {
    require_once __DIR__ . '/../lang.php';
    $lang = getLang();
}

// Get perfect answer threshold for current exercise type
require_once __DIR__ . '/../config.php';
$perfect_threshold = 0; // Default threshold
if (isset($exercise_type) && isset($config_perfect_threshold[$exercise_type])) {
    $perfect_threshold = $config_perfect_threshold[$exercise_type];
}
?>
<div class="history" id="history-container">
    <h3><?php echo $lang['history']; ?></h3>
    
    <!-- Date tabs -->
    <div class="history-tabs" id="history-tabs">
        <!-- Tabs will be generated by JavaScript -->
    </div>
    
    <!-- History list for selected date -->
    <div id="history-list"></div>
    
    <button class="clear-history-btn" id="clear-history-btn" style="display: none;"><?php echo $lang['clear_history']; ?></button>
</div>

<script type="text/javascript">
    var selectedDate = null; // Currently selected date (YYYY-MM-DD format)
    var historyByDate = {}; // History grouped by date
    var perfectThreshold = <?php echo $perfect_threshold; ?>; // Perfect answer threshold for current exercise type
    
    /**
     * Calculate statistics for a date
     * @param {Array} items - History items for the date
     * @returns {Object} Statistics object with correct, wrong, and perfect counts
     */
    function calculateDateStats(items) {
        var correct = 0;
        var wrong = 0;
        var perfect = 0; // Perfect answers (correct on first try, no wrong answers)
        
        items.forEach(function(item) {
            if (!item || item.skipped) return; // Don't count skipped items
            
            correct++; // Each item represents a correct answer eventually
            
            // Count wrong answers
            if (item.wrongAnswers && item.wrongAnswers.length > 0) {
                wrong += item.wrongAnswers.length;
            } else {
                // No wrong answers = perfect answer (correct on first try)
                perfect++;
            }
        });
        
        return {
            correct: correct,
            wrong: wrong,
            perfect: perfect,
            reachedThreshold: perfectThreshold > 0 && perfect >= perfectThreshold
        };
    }
    
    /**
     * Format date to display string
     * @param {string} dateStr - Date string in YYYY-MM-DD format
     * @returns {string} Formatted date string
     */
    function formatDateDisplay(dateStr) {
        if (!dateStr) return '';
        
        var date = new Date(dateStr + 'T00:00:00');
        var today = new Date();
        today.setHours(0, 0, 0, 0);
        
        var yesterday = new Date(today);
        yesterday.setDate(yesterday.getDate() - 1);
        
        var dateOnly = new Date(date);
        dateOnly.setHours(0, 0, 0, 0);
        
        if (dateOnly.getTime() === today.getTime()) {
            return typeof LANG !== 'undefined' ? LANG.today : 'Hôm nay';
        } else if (dateOnly.getTime() === yesterday.getTime()) {
            return typeof LANG !== 'undefined' ? LANG.yesterday : 'Hôm qua';
        } else {
            // Format: DD/MM/YYYY
            var day = String(date.getDate()).padStart(2, '0');
            var month = String(date.getMonth() + 1).padStart(2, '0');
            var year = date.getFullYear();
            return day + '/' + month + '/' + year;
        }
    }
    
    /**
     * Extract date from datetime string
     * @param {string} datetime - Datetime string (e.g., "2024-11-29 14:30:00")
     * @returns {string} Date string in YYYY-MM-DD format
     */
    function extractDate(datetime) {
        if (!datetime) return '';
        return datetime.split(' ')[0]; // Get date part only
    }
    
    /**
     * Group history by date and get unique dates
     * @returns {Array} Array of date strings (YYYY-MM-DD) sorted descending
     */
    function groupHistoryByDate() {
        historyByDate = {};
        
        if (!problemHistory || problemHistory.length === 0) {
            return [];
        }
        
        // Group by date
        problemHistory.forEach(function(item) {
            if (!item) return;
            
            // If no createdAt, use today's date as fallback
            var dateStr = item.createdAt || new Date().toISOString().split('T')[0];
            var date = extractDate(dateStr);
            if (!date) return;
            
            if (!historyByDate[date]) {
                historyByDate[date] = [];
            }
            historyByDate[date].push(item);
        });
        
        // Get unique dates and sort descending (newest first)
        var dates = Object.keys(historyByDate).sort(function(a, b) {
            return b.localeCompare(a); // Descending
        });
        
        // Limit to 7 most recent days
        return dates.slice(0, 7);
    }
    
    /**
     * Check if a date is today
     * @param {string} date - Date string in YYYY-MM-DD format
     * @returns {boolean} True if date is today
     */
    function isToday(date) {
        if (!date) return false;
        var today = new Date();
        today.setHours(0, 0, 0, 0);
        var checkDate = new Date(date + 'T00:00:00');
        checkDate.setHours(0, 0, 0, 0);
        return checkDate.getTime() === today.getTime();
    }
    
    /**
     * Render date tabs
     */
    function renderDateTabs() {
        var dates = groupHistoryByDate();
        var html = '';
        
        if (dates.length === 0) {
            $('#history-tabs').html('');
            return;
        }
        
        // Determine which date should be active
        var activeDate = selectedDate;
        if (!activeDate || !historyByDate[activeDate]) {
            activeDate = dates[0]; // Default to newest date
        }
        
        // Check if today reached threshold
        var todayDate = new Date().toISOString().split('T')[0];
        var todayStats = historyByDate[todayDate] ? calculateDateStats(historyByDate[todayDate]) : null;
        var todayReachedThreshold = todayStats && todayStats.reachedThreshold;
        
        // Highlight history container if today reached threshold
        if (todayReachedThreshold) {
            $('#history-container').addClass('history-container-perfect');
        } else {
            $('#history-container').removeClass('history-container-perfect');
        }
        
        html = '<div class="history-tabs-container">';
        dates.forEach(function(date) {
            var isActive = activeDate === date;
            var stats = calculateDateStats(historyByDate[date] || []);
            var reachedThreshold = stats.reachedThreshold;
            
            // Build tab classes
            var tabClass = 'history-tab';
            if (isActive) {
                tabClass += ' history-tab-active';
            }
            if (reachedThreshold) {
                tabClass += ' history-tab-perfect';
            }
            
            // Calculate statistics for this date
            var correctText = typeof LANG !== 'undefined' ? LANG.correct_count : 'Đúng';
            var wrongText = typeof LANG !== 'undefined' ? LANG.wrong_count : 'Sai';
            var perfectText = typeof LANG !== 'undefined' ? (LANG.perfect_count || 'Hoàn hảo') : 'Hoàn hảo';
            var statsHtml = '<div style="font-size: 85%; margin-top: 3px; color: #666;">' + 
                           correctText + ': ' + stats.correct + ' | ' + 
                           wrongText + ': ' + stats.wrong;
            
            // Add perfect count if threshold is set
            if (perfectThreshold > 0) {
                statsHtml += ' | ' + perfectText + ': ' + stats.perfect;
                if (reachedThreshold) {
                    statsHtml += ' ✓';
                }
            }
            statsHtml += '</div>';
            
            html += '<button class="' + tabClass + '" data-date="' + date + '">' + 
                    formatDateDisplay(date) + statsHtml + '</button>';
        });
        html += '</div>';
        
        $('#history-tabs').html(html);
        
        // Update selectedDate
        selectedDate = activeDate;
        
        // Add click handlers
        $('.history-tab').click(function() {
            var date = $(this).data('date');
            selectDate(date);
        });
    }
    
    /**
     * Select a date and display its history
     * @param {string} date - Date string in YYYY-MM-DD format
     */
    function selectDate(date) {
        selectedDate = date;
        
        // Update tab active state
        $('.history-tab').removeClass('history-tab-active');
        $('.history-tab[data-date="' + date + '"]').addClass('history-tab-active');
        
        // Display history for selected date
        displayHistoryForDate(date);
    }
    
    /**
     * Display history list for a specific date
     * @param {string} date - Date string in YYYY-MM-DD format
     */
    function displayHistoryForDate(date) {
        var html = '';
        var items = historyByDate[date] || [];
        
        if (items.length === 0) {
            html = '<p style="color: #999;">' + (typeof LANG !== 'undefined' ? LANG.no_items_for_date : 'Không có bài nào trong ngày này') + '</p>';
        } else {
            // Sort by time descending (newest first) - if createdAt exists
            // Otherwise maintain current order (which should already be newest first)
            items.sort(function(a, b) {
                if (!a.createdAt && !b.createdAt) return 0; // Maintain order if no timestamps
                if (!a.createdAt) return 1; // Items without timestamp go to bottom
                if (!b.createdAt) return -1;
                return b.createdAt.localeCompare(a.createdAt);
            });
            
            items.forEach(function(item) {
                // Skip invalid items
                if (!item || typeof item.problem === 'undefined') {
                    return;
                }
                
                // Style khác nhau cho bài skipped
                var itemClass = item.skipped ? 'history-item history-item-skipped' : 'history-item';
                var skippedText = typeof LANG !== 'undefined' ? LANG.skipped : 'BỎ QUA';
                var skippedLabel = item.skipped ? '<span style="background-color: #ff9800; color: white; padding: 2px 8px; border-radius: 3px; font-size: 80%; margin-right: 5px; font-weight: bold;">' + skippedText + '</span>' : '';
                
                html += '<div class="' + itemClass + '">';
                html += skippedLabel;
                html += '<span class="history-problem">' + item.problem + '</span> = ';
                html += '<span class="history-correct">' + item.correctAnswer + '</span>';
                
                if (item.wrongAnswers && item.wrongAnswers.length > 0) {
                    html += '; <span class="history-wrong">(' + item.wrongAnswers.join(', ') + ')</span>';
                }
                
                html += '</div>';
            });
        }
        
        $('#history-list').html(html);
    }
    
    /**
     * Display history list (main function - maintains backward compatibility)
     * Uses global variable: problemHistory
     */
    function displayHistory() {
        // Store current selected date before regrouping
        var previousSelectedDate = selectedDate;
        
        // Render tabs first (this will regroup history)
        renderDateTabs();
        
        // Display history for selected date
        var dates = Object.keys(historyByDate).sort(function(a, b) {
            return b.localeCompare(a);
        });
        
        if (dates.length === 0) {
            var noHistoryText = typeof LANG !== 'undefined' ? LANG.no_history : 'Chưa có lịch sử';
            $('#history-list').html('<p style="color: #999;">' + noHistoryText + '</p>');
            return;
        }
        
        // If previous date still exists, keep it selected
        // Otherwise, select the newest date
        if (previousSelectedDate && historyByDate[previousSelectedDate]) {
            selectDate(previousSelectedDate);
        } else {
            selectDate(dates[0]); // Select newest date
        }
    }

    /**
     * Clear history
     * Uses global variable: historyManager (if available), otherwise uses localStorage
     */
    function clearHistory() {
        if (confirmClearHistory()) {
            // Check if using server-side history
            if (typeof historyManager !== 'undefined' && historyManager !== null) {
                clearHistoryOnServer(historyManager, function(err) {
                    if (!err) {
                        problemHistory = [];
                        displayHistory();
                    } else {
                        var errorMsg = typeof LANG !== 'undefined' ? (LANG.clear_history || 'Clear history') + ' error: ' : 'Lỗi khi xóa lịch sử: ';
                        alert(errorMsg + err);
                    }
                });
            } else {
                // Fallback to localStorage (for backward compatibility)
                problemHistory = [];
                // Note: localStorage key should be set in the main file
                if (typeof removeFromStorage === 'function') {
                    // Try to remove from storage if key is known
                    // This is a fallback, main files should handle this
                }
                displayHistory();
            }
        }
    }

    // Event handler for clear history button
    $(function() {
        $('#clear-history-btn').click(function() {
            clearHistory();
        });
    });
</script>

